steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - asocial-nerd-bot
      - --entry-point=asocialNerdBot \
      - --gen2 \
      - --region=europe-west2 \
      - --runtime nodejs16 \
      - --trigger-http \
      - --set-env-vars=[TELEGRAM_BOT_AUTHENTICATION_TOKEN=$TELEGRAM_BOT_AUTHENTICATION_TOKEN, PUBLIC_ENDPOINT=$PUBLIC_ENDPOINT] \
      - --ingress-settings all \
      - --allow-unauthenticated